# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Mikkelsen
email: eric@ericmikkelsen.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericmikkelsen.github.io/" # the base hostname & protocol for your site
twitter_username: ericmikkelsen
github_username:  ericmikkelsen

# Build settings
markdown: kramdown
exclude:
   - node_modules
   - yarn.lock
   - README.md
   - package.json
   - Gemfile
   - Gemfile.lock
   - build.js
   - ericmikkelsen
   - ericmikkelsen.pub

#compression settingscompress_html:
#http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  #endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  #startings: [html, head, body]
